'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自动保存功能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("61666")>  _
        Public Property APIPort() As UShort
            Get
                Return CType(Me("APIPort"),UShort)
            End Get
            Set
                Me("APIPort") = value
            End Set
        End Property

		<Global.System.Configuration.UserScopedSettingAttribute(),
		 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
		 Global.System.Configuration.DefaultSettingValueAttribute("True")>
		Public Property IsFirstStart() As Boolean
            Get
                Return CType(Me("IsFirstStart"),Boolean)
            End Get
            Set
                Me("IsFirstStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property QueryFrequency() As Byte
            Get
                Return CType(Me("QueryFrequency"),Byte)
            End Get
            Set
                Me("QueryFrequency") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property IsCheckPlayerInfoBeforeAdd() As Boolean
            Get
                Return CType(Me("IsCheckPlayerInfoBeforeAdd"),Boolean)
            End Get
            Set
                Me("IsCheckPlayerInfoBeforeAdd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsSystemAutoStart() As Boolean
            Get
                Return CType(Me("IsSystemAutoStart"),Boolean)
            End Get
            Set
                Me("IsSystemAutoStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsCheckUpdateOnStart() As Boolean
            Get
                Return CType(Me("IsCheckUpdateOnStart"),Boolean)
            End Get
            Set
                Me("IsCheckUpdateOnStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsBest30FunctionUnlocked() As Boolean
            Get
                Return CType(Me("IsBest30FunctionUnlocked"),Boolean)
            End Get
            Set
                Me("IsBest30FunctionUnlocked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsDebugModeOn() As Boolean
            Get
                Return CType(Me("IsDebugModeOn"),Boolean)
            End Get
            Set
                Me("IsDebugModeOn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AnomalyFunc_TotalManualQueryTimes() As Long
            Get
                Return CType(Me("AnomalyFunc_TotalManualQueryTimes"),Long)
            End Get
            Set
                Me("AnomalyFunc_TotalManualQueryTimes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AnomalyFunc_IsSolitaryBoxxxPassed() As Boolean
            Get
                Return CType(Me("AnomalyFunc_IsSolitaryBoxxxPassed"),Boolean)
            End Get
            Set
                Me("AnomalyFunc_IsSolitaryBoxxxPassed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AnomalyFunc_IsPlayersCountBiggerThan10() As Boolean
            Get
                Return CType(Me("AnomalyFunc_IsPlayersCountBiggerThan10"),Boolean)
            End Get
            Set
                Me("AnomalyFunc_IsPlayersCountBiggerThan10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AnomalyFunc_IsQuerySpecialOrder() As Boolean
            Get
                Return CType(Me("AnomalyFunc_IsQuerySpecialOrder"),Boolean)
            End Get
            Set
                Me("AnomalyFunc_IsQuerySpecialOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AnomalyFunc_IsConnectStringCorrect() As Boolean
            Get
                Return CType(Me("AnomalyFunc_IsConnectStringCorrect"),Boolean)
            End Get
            Set
                Me("AnomalyFunc_IsConnectStringCorrect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AnomalyFunc_IsTriggeredUnlockEffects() As Boolean
            Get
                Return CType(Me("AnomalyFunc_IsTriggeredUnlockEffects"),Boolean)
            End Get
            Set
                Me("AnomalyFunc_IsTriggeredUnlockEffects") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsUnlockedAnomalyFunc() As Boolean
            Get
                Return CType(Me("IsUnlockedAnomalyFunc"),Boolean)
            End Get
            Set
                Me("IsUnlockedAnomalyFunc") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Team123it.Arcaea.Solimmr.[Global].My.MySettings
            Get
                Return Global.Team123it.Arcaea.Solimmr.[Global].My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
