'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Team123it.Arcaea.Solimmr.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 (C)Copyright 2015-2020 123 Open-Source Organization. All rights reserved. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Copyright_en_US() As String
            Get
                Return ResourceManager.GetString("Copyright_en_US", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 (C)版权所有 2015-2020 123 Open-Source Organization. 保留所有权利. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Copyright_zh_CN() As String
            Get
                Return ResourceManager.GetString("Copyright_zh_CN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 solimmr.exe [-?|-sysrun|-debug] 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Usage() As String
            Get
                Return ResourceManager.GetString("Usage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 -?     Show this help
        '''-sysrun     Start Solitary Memories as System Auto-Run Mode(Not show the starting window and the main window)
        '''-debug     Enable Debug Mode(Show BotArcAPI Window) 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UsageList_en_US() As String
            Get
                Return ResourceManager.GetString("UsageList_en_US", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 -?     显示本帮助
        '''-sysrun     以开机自启模式启动Solitary Memories(不显示启动窗口和主窗口)
        '''-debug     启用调试(Debug)模式(显示BotArcAPI窗口) 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UsageList_zh_CN() As String
            Get
                Return ResourceManager.GetString("UsageList_zh_CN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Usage: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UsagePrefix_en_US() As String
            Get
                Return ResourceManager.GetString("UsagePrefix_en_US", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用法： 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UsagePrefix_zh_CN() As String
            Get
                Return ResourceManager.GetString("UsagePrefix_zh_CN", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
